### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ahaaje** [alexandrubau/messenger-azure-queue-transport#14]
Hi,

Will there be a new release so that packages can be updated with the latest bug fix, please?

**Comment by SpartakusMd** [comment]
@alexandrubau  could you tag a new version so we could use it in our projects?

**Comment by alexandrubau** [comment]
Of course, right away.

**Comment by alexandrubau** [comment]
I'm looking for a little bit of help on this package. @SpartakusMd   would you like to become maintainer for this repository?

**Comment by SpartakusMd** [comment]
@alexandrubau I don't have much free time, but I can give it a shot. What are your plans for the project? With what exactly may I help?

**Comment by alexandrubau** [comment]
There are no plans right now. I find it useful to have a second opinion in regards to submitted pull requests.

**Comment by SpartakusMd** [comment]
Will be happy to help with that!
