### ISSUE TITLE
Remove flattened exception for failure_transport

### ISSUE THREAD

**Issue by alexandrubau** [alexandrubau/messenger-azure-queue-transport#2]
After the message failed to be sent it will be moved to the failure_transport queue.
Unfortunatelly Azure Storage doesn't allow the message to be bigger than 48 kb.
We will have to remove the exception trace before saving the message into Azure Queues.
Maybe provide an option?

**Comment by SpartakusMd** [comment]
@alexandrubau do you already have ideas about how to approach this bug? I would like to fix this as we're also impacted.

**Comment by alexandrubau** [comment]
What I remember from that time is that maybe we could add another option when configuring the queue such as `error_stack_trace` that would parse the generated error stack trace and extract only the last error instead of storing the entire stack trace.

**Comment by SpartakusMd** [comment]
Hey @alexandrubau, I'm preparing a fix for this bug. My approach would be to limit the stack trace in the exception to 5 elements. I see benefits in keeping the flattened exception with the previous exception for debug purposes. What do you think?

But I have a question related to the symfony supported versions. The place the exception is stored changed in symfony/messenger:5.2

> The `RedeliveryStamp` will no longer be populated with error data. This information is now stored in the `ErrorDetailsStamp` instead.

Seeing as symfony 5.4 is the oldest maintained version, could we remove support for symfony <5.2? If not, I will include a backward compatibility layer.

**_Update_**: used a compatibility layer.

**Comment by alexandrubau** [comment]
I agree with your suggestion. We can keep only the last X elements from the exception stack trace. I'm thinking that maybe we can make this configurable. I'm proposing the parameter `stack_trace_limit`, and it can be used like so: `stack_trace_limit: 5`. What do you think?

In my opinion we should have a thin compatibility layer in order to support Symfony versions < 5.2.

**Comment by alexandrubau** [comment]
Please ignore my recommendation for `stack_trace_limit` configuration param. I see that you already created a Pull Request and the behaviour to trim stack trace is enabled by default. And I think this is better.

**Comment by SpartakusMd** [comment]
I agree with the compatibility, it wasn't hard to do, but allows the package to be used by more users.

I was also thinking to make it configurable. But in the end avoided complexity. We can add it later if it will be necessary.
